Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1749, in robot_informes_masvoz
    archivoDescargado,mensaje = descargar_colas_individual_tramos_masvoz(frame=frame,pagina=pagina,fecha_inicio=fechaDatos,cola=cola)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 447, in descargar_colas_individual_tramos_masvoz
    frame.locator('#etime').press_sequentially(str(str_fecha_fin_filtro))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 17279, in press_sequentially
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 634, in press_sequentially
    await self.type(text, delay=delay, timeout=timeout, noWaitAfter=noWaitAfter)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 621, in type
    return await self._frame.type(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 720, in type
    await self._channel.send("type", locals_to_params(locals()))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Locator.press_sequentially: Target page, context or browser has been closed
Call log:
waiting for frame_locator("#estadisticas_0").locator("#etime")
  -   locator resolved to <input id="etime" type="text" class="input-small"/>
  - elementHandle.type("26-07-2024")

Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1749, in robot_informes_masvoz
    archivoDescargado,mensaje = descargar_colas_individual_tramos_masvoz(frame=frame,pagina=pagina,fecha_inicio=fechaDatos,cola=cola)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 447, in descargar_colas_individual_tramos_masvoz
    frame.locator('#etime').press_sequentially(str(str_fecha_fin_filtro))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 17279, in press_sequentially
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 634, in press_sequentially
    await self.type(text, delay=delay, timeout=timeout, noWaitAfter=noWaitAfter)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 621, in type
    return await self._frame.type(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 720, in type
    await self._channel.send("type", locals_to_params(locals()))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Locator.press_sequentially: Target page, context or browser has been closed
Call log:
waiting for frame_locator("#estadisticas_0").locator("#etime")
  -   locator resolved to <input id="etime" type="text" class="input-small"/>
  - elementHandle.type("26-07-2024")

Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1747, in robot_informes_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(navegador=navegador,pagina=pagina,mi_playwright=mi_playwright)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 276, in obtener_web_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(seccion=seccion,maximizado=maximizado,navegador=navegador,pagina=pagina,mi_playwright=mi_playwright,reiniciar_navegador=True)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 244, in obtener_web_masvoz
    pagina = abrir_pagina(navegador=navegador,url=url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 209, in abrir_pagina
    pagina = navegador.new_page()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 13868, in new_page
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
Exception: Browser.new_page: Connection closed while reading from the driver
Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 2041, in robot_informes_masvoz
    exportar_tramos_faltantes(lista_informes=lista_informes,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1487, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1747, in robot_informes_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(navegador=navegador,pagina=pagina,mi_playwright=mi_playwright)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 244, in obtener_web_masvoz
    pagina = abrir_pagina(navegador=navegador,url=url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 209, in abrir_pagina
    pagina = navegador.new_page()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 13868, in new_page
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
Exception: Browser.new_page: Connection closed while reading from the driver
Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1749, in robot_informes_masvoz
    archivoDescargado,mensaje = descargar_colas_individual_tramos_masvoz(frame=frame,pagina=pagina,fecha_inicio=fechaDatos,cola=cola)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 444, in descargar_colas_individual_tramos_masvoz
    frame.locator('#stime').press_sequentially(str(str_fecha_inicio_filtro))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 17279, in press_sequentially
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 634, in press_sequentially
    await self.type(text, delay=delay, timeout=timeout, noWaitAfter=noWaitAfter)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 621, in type
    return await self._frame.type(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 720, in type
    await self._channel.send("type", locals_to_params(locals()))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Locator.press_sequentially: Target page, context or browser has been closed
Call log:
waiting for frame_locator("#estadisticas_0").locator("#stime")
  -   locator resolved to <input id="stime" type="text" class="input-small"/>
  - elementHandle.type("26-07-2024")

Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1747, in robot_informes_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(navegador=navegador,pagina=pagina,mi_playwright=mi_playwright)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 276, in obtener_web_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(seccion=seccion,maximizado=maximizado,navegador=navegador,pagina=pagina,mi_playwright=mi_playwright,reiniciar_navegador=True)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 241, in obtener_web_masvoz
    navegador = abrir_navegador(mi_playwright=mi_playwright)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 204, in abrir_navegador
    navegador = mi_playwright.chromium.launch(headless=oculto)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 14155, in launch
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
Exception: BrowserType.launch: Connection closed while reading from the driver
Errror:
Traceback (most recent call last):
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1482, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 2041, in robot_informes_masvoz
    exportar_tramos_faltantes(lista_informes=lista_informes,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1487, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,mi_playwright=mi_playwright,mensajes=mensajes)
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1747, in robot_informes_masvoz
    mi_playwright,navegador,pagina,frame = obtener_web_masvoz(navegador=navegador,pagina=pagina,mi_playwright=mi_playwright)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 244, in obtener_web_masvoz
    pagina = abrir_pagina(navegador=navegador,url=url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 209, in abrir_pagina
    pagina = navegador.new_page()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 13868, in new_page
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
Exception: Browser.new_page: Connection closed while reading from the driver
