2024-07-29 11:27:39,654 ERROR exportar_tramos_faltantes(1519) Error:
Traceback (most recent call last):
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1517, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1807, in robot_informes_masvoz
    archivoDescargado,mensaje = descargar_colas_individual_tramos_masvoz(frame=frame,pagina=pagina,fecha_inicio=fechaDatos,cola=cola)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 513, in descargar_colas_individual_tramos_masvoz
    mensaje += f"Se ha exportado la cola {cola} {nombre_archivo} Desde el {str_fecha_inicio_filtro} {str_hora_inicio} al {str_fecha_fin_filtro} {str_hora_fin}"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
2024-07-29 11:34:25,992 ERROR exportar_tramos_faltantes(1519) Error:
Traceback (most recent call last):
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1517, in exportar_tramos_faltantes
    robot_informes_masvoz(fecha_hora_inicio=fecha,lista_informes=['colas_individual_tramos'],cola = cola,recuperar_datos=True,navegador=navegador,pagina=pagina,frame=frame,mi_playwright=mi_playwright,mensajes=mensajes)
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1807, in robot_informes_masvoz
    archivoDescargado,mensaje = descargar_colas_individual_tramos_masvoz(frame=frame,pagina=pagina,fecha_inicio=fechaDatos,cola=cola)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 513, in descargar_colas_individual_tramos_masvoz
    mensaje += f"Se ha exportado la cola {cola} {nombre_archivo} Desde el {str_fecha_inicio_filtro} {str_hora_inicio} al {str_fecha_fin_filtro} {str_hora_fin}"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
2024-07-29 11:53:26,987 ERROR exportar_tramos_faltantes(1510) Error:
Traceback (most recent call last):
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1508, in exportar_tramos_faltantes
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 1797, in robot_informes_masvoz
    mensajes.append(f"Empezando a sacar el informe_{tipoInforme}")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Vscode\Python\python_web\exportarMasVozPlaywrightTodoALaVez.py", line 492, in descargar_colas_individual_tramos_masvoz
    frame.get_by_role("option",name=cola).first.click()
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 15093, in click
    self._sync(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for frame_locator("#estadisticas_0").get_by_role("option", name="VY S1 Grupos Ca K").first

